### ISSUE TITLE
Custom Drawable with DayViewDecorator API

### ISSUE THREAD

**Issue by arimorty** [prolificinteractive/material-calendarview#133]
I am using your library in my project and I am loving it. Thanks. 

The line `this.customBackground = drawable.getConstantState().newDrawable(getResources())` in DayView is making it very hard to work with custom drawables, since getConstantState() will return null in custom drawables that do not override getConstantState().  I might be missing something, but, in my opinion, there appears to be no benefit from using `newDrawable()` instead of using the passed drawable directly. I think that it takes away a lot from the library's flexibility, as in my case with custom drawables.

**Comment by dandc87** [comment]
I agree with you, this should be fixed. When I did this, the issue was with sharing the drawable that was stateful. This is especially apparent if you change the selection setter to just `this.selectionDrawable = drawable;`. Once you select a day, it goes crazy. The solution at the time was to use `getConstantState().newDrawable()` to get a separate instance of the drawable so it wouldn't share state. I naively assumed that this would just work all the time.

I'm going to slate this for the post 1.0 release. I expect we can fix this by drawing the selection drawable manually, instead of setting it as the view's background.

**Comment by arimorty** [comment]
I figured there was a reason for it, and, although you are going to fix it, I am still glad I now know what it was used for to begin with.

Thanks again for such a great library!

**Comment by Maragues** [comment]
Hi, this is still happening 7 months later. Any chance a fix is on its way?

Thanks!
