### ISSUE TITLE
setCalendarDisplayMode(CalendarMode.WEEKS) wrong week when Date selected

### ISSUE THREAD

**Issue by markuspaschke** [prolificinteractive/material-calendarview#222]
When you "collapse" the Calendar with .setCalendarDisplayMode(CalendarMode.WEEKS), the week displayed is one week to early, when using Monday as first day of the week. (Only working when i select the Sunday)
[BUG]

**Comment by victorileaf** [comment]
its not working even if i set to Sunday .. on lollipop and above.
Works on pre-lolliop devices. if first day is Sunday.

problem with setCurrentDate
date set to Saturday or Sunday of the week in Week View.

eg: 
In weekview (Today:30/6/16)
CurrentDate: CalendarDay{2016-2-26} selected Date: CalendarDay{2016-2-30}

**Comment by Nuclominus** [comment]
Same bug on marshmallow, but week switches to the desired week if setCurrentTime set for Sunday

**Comment by MalderAndroid** [comment]
In my case, I has this bug in the Marshmallow version.

**Comment by joecizac** [comment]
Adding `dayDiff += (Calendar.DAY_OF_WEEK_IN_MONTH - firstDayOfTheWeek) % 7;` between line 69-70 in WeekPagerAdapter#weekNumberDifference(...) seems to fix this.
Expose 'firstDayOfTheWeek' in CalendarPagerAdapter with 'public static' modifier.

**Comment by quentin41500** [comment]
@joecizac Thanks for your answer we are going to check that out

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!

**Comment by joecizac** [comment]
the issue still persists in nexus 5 running on 6.0.1...dunno why

**Comment by victorileaf** [comment]
yes issue still persists in marshmallow ... i have use a hack to scroll the pager in Week view. its working fine in lolliop and below i think

**Comment by joecizac** [comment]
And the problem aggravates with setMaximumDate

**Comment by ekchang** [comment]
@joecizac @victorileaf Can you provide full details on the MCV configuration you are using to repro this issue?

**Comment by joecizac** [comment]
mCalendarView = (MaterialCalendarView) parent.findViewById(R.id.cal_week);
        mCalendarView.setShowOtherDates(MaterialCalendarView.SHOW_ALL);
        mCalendarView.setSelectedDate(now.getTime());
        mCalendarView.setCurrentDate(CalendarDay.from(now), false);
        mCalendarView.setMaximumDate(now.getTime());

**Comment by ekchang** [comment]
For 1.3.0 and below, you should call `setMaxDate` before `Current/Selected`; min/max does things which rebuild the adapters and is especially sensitive for Week mode.

**Comment by joecizac** [comment]
The issue is with Marshmallow and N preview.

**Comment by ekchang** [comment]
No, it's not platform specific. I can repro this even on a 5.1 device. This snippet will break on `1.4.0` for example:
```
CalendarDay today = CalendarDay.from(2016, 4, 25);

widget.state().edit()
  .setMaximumDate(today)
  .setCalendarDisplayMode(CalendarMode.WEEKS)
  .commit();

widget.setCurrentDate(today);
widget.setSelectedDate(today);
```

**Comment by joecizac** [comment]
So this bug should be re-opened right?

**Comment by ekchang** [comment]
It has already been reopened.

**Comment by joecizac** [comment]
still persists in nexus 5 running 6.0.1
running the sample app

**Comment by joecizac** [comment]
There is still something to do with minDate.
If not set, the above issue persists in nexus 5 with 6.0.1.
If minDate is set, the calendar is not drawn in Xiaomi Redmi 2 running 4.4.4, removing minDate solves it though.

**Comment by lopezzbelgium** [comment]
I still have this issue on 1.4.0 when using monday as firstDayOfWeek
